### PR TITLE
DSA implementation using C

### PR DESCRIPTION
**Pull request by BAKCHODGUNDA**
Please mark this as hacktober accpeted!!

### CODE REVIEW

**Comment by wafarifki** [comment]
> Please mark this as hacktober accpeted!!

don't pull in here bro..

**Comment by BAKCHODGUNDA** [comment]
> > Please mark this as hacktober accpeted!!
> 
> don't pull in here bro..

I didn't get you, what exactly do you mean?

**Comment by wafarifki** [comment]
> > > Please mark this as hacktober accpeted!!
> > 
> > 
> > don't pull in here bro..
> 
> I didn't get you, what exactly do you mean?

do not pull requests to this repository, please pull requests to the following repository bro.

https://github.com/wafarifki/Hacktoberfest_2021

**Comment by BAKCHODGUNDA** [comment]
> > > > Please mark this as hacktober accpeted!!
> > > 
> > > 
> > > don't pull in here bro..
> > 
> > 
> > I didn't get you, what exactly do you mean?
> 
> do not pull requests like this to this repository, please pull requests to the following repository bro.
> 
> https://github.com/wafarifki/Hacktoberfest_2021

Ok bro, sorry, didn't knew. I am adding  right away!

**Comment by wafarifki** [comment]
> > > > > Please mark this as hacktober accpeted!!
> > > > 
> > > > 
> > > > don't pull in here bro..
> > > 
> > > 
> > > I didn't get you, what exactly do you mean?
> > 
> > 
> > do not pull requests like this to this repository, please pull requests to the following repository bro.
> > https://github.com/wafarifki/Hacktoberfest_2021
> 
> Ok bro, sorry, didn't knew. I am adding right away!

ok bro no problem for this :)

**Pull request closed without merging**
